name: PMK-LobbyUtils
main: fr.pmk_lobbyutils.MainLobbyUtils
version: 1.0
author: PumpMyKins

commands:
  hbclist:
      description: Commande d affichage de la liste des serveurs
      usage: /hbclist
  hbcserver:
      description: Commandes de mises a jour des informations des serveurs
      usage: /hbcserver
  spawn:
      description: Commande de spawn
      usage: /spawn
     